export const LOTERIA_CARDS = [
  { id: 1, nameEs: 'El Gallo', nameEn: 'The Rooster' },
  { id: 2, nameEs: 'El Diablo', nameEn: 'The Devil' },
  { id: 3, nameEs: 'La Dama', nameEn: 'The Lady' },
  { id: 4, nameEs: 'El Catrín', nameEn: 'The Gentleman' },
  { id: 5, nameEs: 'El Paraguas', nameEn: 'The Umbrela' },
  { id: 6, nameEs: 'La Sirena', nameEn: 'The Mermaid' },
  { id: 7, nameEs: 'La Escalera', nameEn: 'The Ladder' },
  { id: 8, nameEs: 'La Botella', nameEn: 'The Bottle' },
  { id: 9, nameEs: 'El Barril', nameEn: 'The Barrel' },
  { id: 10, nameEs: 'El Árbol', nameEn: 'The Tree' },
  { id: 11, nameEs: 'El Melón', nameEn: 'The Melon' },
  { id: 12, nameEs: 'El Valiente', nameEn: 'The Brave Man' },
  { id: 13, nameEs: 'El Gorrito', nameEn: 'The Little Bonnet' },
  { id: 14, nameEs: 'La Muerte', nameEn: 'Death' },
  { id: 15, nameEs: 'La Pera', nameEn: 'The Pear' },
  { id: 16, nameEs: 'La Bandera', nameEn: 'The Flag' },
  { id: 17, nameEs: 'El Bandolón', nameEn: 'The Banjo' },
  { id: 18, nameEs: 'El Violoncello', nameEn: 'The Violin' },
  { id: 19, nameEs: 'La Garza', nameEn: 'The Flamingo' },
  { id: 20, nameEs: 'El Pájaro', nameEn: 'The Bird' },
  { id: 21, nameEs: 'La Mano', nameEn: 'The Hand' },
  { id: 22, nameEs: 'La Bota', nameEn: 'The Boot' },
  { id: 23, nameEs: 'La Luna', nameEn: 'The Moon' },
  { id: 24, nameEs: 'El Cotorro', nameEn: 'The Parrot' },
  { id: 25, nameEs: 'El Borracho', nameEn: 'The Drunk' },
  { id: 26, nameEs: 'El Negrito', nameEn: 'The Black Man' },
  { id: 27, nameEs: 'El Corazón', nameEn: 'The Heart' },
  { id: 28, nameEs: 'La Sandía', nameEn: 'The Watermelon' },
  { id: 29, nameEs: 'El Tambor', nameEn: 'The Drum' },
  { id: 30, nameEs: 'El Camarón', nameEn: 'The Shrimp' },
  { id: 31, nameEs: 'Las Jaras', nameEn: 'The Arrows' },
  { id: 32, nameEs: 'El Músico', nameEn: 'The Musician' },
  { id: 33, nameEs: 'La Araña', nameEn: 'The Spider' },
  { id: 34, nameEs: 'El Soldado', nameEn: 'The Soldier' },
  { id: 35, nameEs: 'La Estrella', nameEn: 'The Star' },
  { id: 36, nameEs: 'El Cazo', nameEn: 'The Golden Tray' },
  { id: 37, nameEs: 'El Mundo', nameEn: 'The World' },
  { id: 38, nameEs: 'El Apache', nameEn: 'The Apache' },
  { id: 39, nameEs: 'El Nopal', nameEn: 'The Cactus' },
  { id: 40, nameEs: 'El Alacrán', nameEn: 'The Scorpion' },
  { id: 41, nameEs: 'La Rosa', nameEn: 'The Rose' },
  { id: 42, nameEs: 'La Calavera', nameEn: 'The Skull' },
  { id: 43, nameEs: 'La Campana', nameEn: 'The Bell' },
  { id: 44, nameEs: 'El Cantarito', nameEn: 'The Pitcher' },
  { id: 45, nameEs: 'El Venado', nameEn: 'The Deer' },
  { id: 46, nameEs: 'El Sol', nameEn: 'The Sun' },
  { id: 47, nameEs: 'La Corona', nameEn: 'The Crown' },
  { id: 48, nameEs: 'La Chalupa', nameEn: 'The Rowboat' },
  { id: 49, nameEs: 'El Pino', nameEn: 'The Pine Tree' },
  { id: 50, nameEs: 'El Pescado', nameEn: 'The Fish' },
  { id: 51, nameEs: 'La Palma', nameEn: 'The Palm Tree' },
  { id: 52, nameEs: 'La Maceta', nameEn: 'The Flowerpot' },
  { id: 53, nameEs: 'El Arpa', nameEn: 'The Harp' },
  { id: 54, nameEs: 'La Rana', nameEn: 'The Frog' }
];

export const LOTERIA_CARD_COUNT = LOTERIA_CARDS.length;
